/**
 * One repo every agent can reach, whichever repo it is working in.
 *
 * Tier 1 put an agent's memory on a ref inside the codebase it was about, which is
 * the right place for it and is also the reason two agents can never hear each
 * other: the beadcause advocate writes into the beadcause checkout, the sophab
 * advocate writes into sophab's, and neither ref is visible from the other side. A
 * shared place is not an optimisation of that, it is the missing half.
 *
 * `~/.config/beadcause` is already that place — it is the one directory every
 * instance of every agent on this Mac has in common, and it already holds the state
 * whose loss hurts. Making it a git repo therefore buys two things at once:
 *
 * 1. **A home for the cross-agent refs** in lib/memory.js. They ride here for the
 *    same reason session logs ride on refs elsewhere: a ref outside `refs/heads/*`
 *    and `refs/tags/*` touches no working tree, so the daemon can commit one while
 *    something else is rewriting `config.json` beside it.
 * 2. **History and recovery for the state files**, which was being done by hand —
 *    `config.json.bak-20260808` and `config.json.bak-scope` are sitting in that
 *    directory right now, made with `cp` at moments somebody was nervous. A commit
 *    after each write is the same instinct, automated, and it answers "what did this
 *    say before the advocate rewrote it" without anyone having remembered to ask.
 *
 * **The .gitignore is written before `git init`, and that ordering is not tidiness.**
 * That directory holds `android-keystore.jks` — the release signing key for the
 * Android app — and its password file beside it. A `git init && git add -A` there
 * commits a signing key into a history that is then hard to truly remove. So the
 * ignore file lands first, and `commit()` re-checks the staged list against
 * `FORBIDDEN` every single time rather than trusting that it did: an ignore rule is
 * one `git add -f` or one edited `.gitignore` away from not applying, and the cost
 * of being wrong once is a leaked key.
 *
 * Nothing here has a remote and nothing here pushes. This is local history, on a
 * repo whose contents are a token, a tailnet layout, and whatever an agent said.
 *
 * **A losable snapshot is fine, and that is deliberate.** The daemon is not the only
 * process that writes here — `bin/status.js` and `npm run configure` do too — so two
 * of them can collide on `index.lock` and one commit fails. It is logged and
 * dropped, because the state file itself is already safely on disk (lib/atomic.js
 * owns that half) and the next write's `add -A` picks up both changes anyway. The
 * cost of losing this race is one missing line of history, not one missing file.
 */
import fs from 'node:fs';
import path from 'node:path';
import { CONFIG_DIR } from './config.js';
import { git, ok } from './gitref.js';

/**
 * What must never be committed, checked against the staged list at every commit.
 *
 * Deliberately matched on the path rather than on content: the point is to be
 * unmissable and to fail closed, not to be clever. Anything matching here aborts the
 * commit outright instead of being quietly unstaged — a snapshot that silently drops
 * files is a backup you find out about when you need it.
 */
const FORBIDDEN = [/(^|\/)[^/]*\.(jks|keystore|p12|pem|key)$/i, /(^|\/)android-keystore\./i];

/**
 * The ignore file, written before the repo exists.
 *
 * Every line here is something that is either dangerous (the signing key), large and
 * regenerated (the check PNGs are 150–260KB each and are rewritten by every
 * `phone-check` run), or pure churn — `status.json` is rewritten every few seconds by
 * lib/activity.js and a history of it would be noise deep enough to hide the state
 * changes that matter.
 */
const GITIGNORE = `# Written by lib/commonrepo.js before this directory became a repo.
#
# The first block is the one that matters: android-keystore.jks is the release
# signing key for the Android app, and a key committed once is in the history
# forever. lib/commonrepo.js re-checks the staged list at every commit, so editing
# this file is not enough to get one in — but do not test that.
android-keystore.jks
android-keystore.properties
*.jks
*.keystore
*.p12
*.pem

# The tailnet certificate and its private key (lib/tls.js). Fetched by \`tailscale
# cert\`, re-fetchable at any time, and the key is matched by FORBIDDEN — so an
# un-ignored one does not leak, it aborts every snapshot from then on.
tls/
*.key
*.crt

# Check output: regenerated by scripts/phone-check.mjs and scripts/console-check.mjs,
# 150-260KB a piece, and never the thing you want the history of.
*.png

# Churn. status.json is rewritten every few seconds by lib/activity.js; logs/ is the
# streamed output of every agent run; workers/ is scratch.
status.json
logs/
workers/

# The atomic writer's temp files, in the window before the rename.
.*.tmp-*
`;

/** Where it lives. A function, not a constant: see the import cycle note in `snapshot`. */
const dir = () => CONFIG_DIR;

/** Is this directory already a repo? Cheap, and the answer is usually yes. */
async function initialised() {
  const out = await ok(git(dir(), ['rev-parse', '--git-dir']));
  return Boolean(out);
}

/**
 * Add any rule this file has gained since that directory became a repo.
 *
 * The ignore file was written once, before `git init`, and never looked at again — so
 * until now every rule added to `GITIGNORE` afterwards protected fresh installs only.
 * That was survivable while the list was static, and stopped being survivable the
 * moment `tls/` joined it: the private key underneath is matched by `FORBIDDEN`, so an
 * install with a stale ignore file does not leak the key — it refuses every commit from
 * then on, and a history that has quietly stopped is exactly what this repo exists to
 * prevent.
 *
 * Appended, never rewritten: the file is yours to edit, and a rule you added by hand
 * must survive an upgrade. Only non-comment lines are compared, so the commentary here
 * can be reworded without every install growing a copy of it.
 */
function topUpIgnore(file) {
  const rules = (text) =>
    text
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#'));
  let current;
  try {
    current = fs.readFileSync(file, 'utf8');
  } catch {
    return;
  }
  const have = new Set(rules(current));
  const missing = rules(GITIGNORE).filter((rule) => !have.has(rule));
  if (!missing.length) return;
  fs.appendFileSync(file, `\n# Added by lib/commonrepo.js — rules this file predates.\n${missing.join('\n')}\n`);
  console.log(`[beadcause] common repo: ignoring ${missing.join(' ')} — added to ${file}`);
}

/**
 * Make the common repo exist, and return where it is.
 *
 * Idempotent and safe to call on every write — the check is one `rev-parse` against
 * a directory that is already warm. `--initial-branch=main` because git otherwise
 * prints a paragraph about `master` to stderr on every init, and the branch name is
 * never seen by anyone here anyway.
 */
export async function ensureRepo() {
  const d = dir();
  fs.mkdirSync(d, { recursive: true });
  const ignore = path.join(d, '.gitignore');
  // Before the init, always: see the note at the top of the file.
  if (!fs.existsSync(ignore)) fs.writeFileSync(ignore, GITIGNORE, { mode: 0o600 });
  else topUpIgnore(ignore);
  if (!(await initialised())) {
    await git(d, ['init', '--initial-branch=main', '-q']);
  }
  return d;
}

/** Everything git would commit right now, as repo-relative paths. */
async function staged(d) {
  const out = await git(d, ['diff', '--cached', '--name-only']);
  return out.split('\n').filter(Boolean);
}

/**
 * Commit whatever has changed, refusing outright if a secret got staged.
 *
 * Returns the new commit's sha, or null when there was nothing to commit — which is
 * the common case, because this is called after writes that often rewrite a file
 * with identical bytes.
 */
export async function commit(reason = 'state') {
  const d = await ensureRepo();
  await git(d, ['add', '-A']);
  const files = await staged(d);
  if (!files.length) return null;

  const forbidden = files.filter((f) => FORBIDDEN.some((re) => re.test(f)));
  if (forbidden.length) {
    // Unstage before throwing: leaving a signing key sitting in the index means the
    // next commit from anywhere — a human running `git commit` in that directory to
    // see what this thing does — picks it up.
    await ok(git(d, ['reset', '-q']));
    throw new Error(`refusing to commit ${forbidden.join(', ')} — see FORBIDDEN in lib/commonrepo.js`);
  }

  await git(d, ['commit', '-q', '-m', reason]);
  return (await git(d, ['rev-parse', 'HEAD'])).trim();
}

/* --------------------------------------------------- the debounced snapshot */

/**
 * State is written in bursts, so committing per write would be mostly empty commits.
 *
 * A single advocate cycle rewrites `advocates.json` three or four times in a second
 * — cooldown, attempt count, last proposal. Those are one event to a human reading
 * the history back, and eight commits' worth of `git log` to scroll past. So a write
 * *schedules* a commit and the reasons accumulate; the commit that lands names all
 * of them.
 *
 * `unref()` on the timer matters: without it a scheduled snapshot keeps the process
 * alive, which turns every short-lived CLI in bin/ into something that hangs for two
 * seconds at exit for no reason the user can see.
 */
let timer = null;
let reasons = new Set();
let inFlight = null;

export function snapshot(reason = 'state', { delayMs = 2000 } = {}) {
  reasons.add(reason);
  if (timer) return;
  timer = setTimeout(() => {
    timer = null;
    const message = [...reasons].sort().join(', ');
    reasons = new Set();
    inFlight = commit(message).catch((err) => {
      // A snapshot that cannot be taken must never break the write it was taken of.
      // The state file is already safely on disk — this is the history, not the data.
      console.error(`[beadcause] common repo snapshot failed: ${err.message.split('\n')[0]}`);
      return null;
    });
  }, delayMs);
  timer.unref?.();
}

/**
 * Take any pending snapshot now and wait for it. For tests and for shutdown, where
 * "in two seconds" is after the process is gone.
 */
export async function flush() {
  if (timer) {
    clearTimeout(timer);
    timer = null;
    const message = [...reasons].sort().join(', ');
    reasons = new Set();
    inFlight = commit(message);
  }
  const p = inFlight;
  inFlight = null;
  return p ? p.catch(() => null) : null;
}

/**
 * The history of the state files, newest first — `git log` for someone who is not
 * standing in that directory.
 */
export async function history({ limit = 50 } = {}) {
  const log = await ok(git(dir(), ['log', `--max-count=${limit}`, '--format=%H%x00%aI%x00%s']));
  if (!log) return [];
  return log
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      const [commit, at, subject] = line.split('\0');
      return { commit, at, subject };
    });
}
