#!/usr/bin/env bash
#
# Install beadcause as a login-time background service on macOS.
#
#   npm run install-service
#
# Everything machine-specific is discovered here rather than committed: the plist is
# generated with *this* user's home, node binary and checkout path. A checked-in
# plist cannot work on a second machine — node alone moves between
# /opt/homebrew/bin, /usr/local/bin and a dozen nvm paths.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LABEL="n8l.beadcause"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG="$HOME/Library/Logs/beadcause.log"
LEGACY_LABELS=("com.neadamthal.beadcause" "com.beadcause")

say()  { printf '\033[1m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m warn\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31merror\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- prerequisites

[ "$(uname -s)" = "Darwin" ] || die "this installer is macOS-only (it uses launchd)."

NODE="$(command -v node || true)"
[ -n "$NODE" ] || die "node not found. Install Node 20+ (brew install node) and re-run."
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || die "node $NODE_MAJOR is too old; beadcause needs 20+."

# launchd starts with a bare PATH, so `bd` has to be found by absolute path or live
# somewhere the plist's PATH covers. Fail now rather than at the first poll.
BD="$(command -v bd || true)"
[ -n "$BD" ] || die "the beads CLI (bd) is not on your PATH. Install it first — beadcause is a front-end for it."

if [ ! -d "$HOME/beads" ]; then
  warn "no ~/beads directory: beadcause serves every ~/beads/*/.beads workspace and will find none."
fi

command -v tailscale >/dev/null 2>&1 || \
  warn "tailscale not found. beadcause binds to 127.0.0.1 and your Tailscale IP; without it, only this Mac can reach it."

# ------------------------------------------------------------------- dependencies

say "installing dependencies"
( cd "$ROOT" && npm install --silent )

# ------------------------------------------------------------ migrate old install

# Labels this service has been known by. Leaving an old one loaded would leave two
# daemons fighting over port 4318 — the loser exits, but which one loses is a race.
for legacy in "${LEGACY_LABELS[@]}"; do
  legacy_plist="$HOME/Library/LaunchAgents/$legacy.plist"
  if launchctl list 2>/dev/null | grep -q "$legacy" || [ -f "$legacy_plist" ]; then
    say "removing the previous $legacy service (now $LABEL)"
    launchctl bootout "gui/$(id -u)/$legacy" 2>/dev/null || true
    rm -f "$legacy_plist"
  fi
done

# --------------------------------------------------------------------- the plist

say "writing $PLIST"
mkdir -p "$HOME/Library/LaunchAgents" "$(dirname "$LOG")"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/install.sh. Re-run it rather than editing by hand. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>

  <key>ProgramArguments</key>
  <array>
    <string>$NODE</string>
    <string>$ROOT/bin/beadcause.js</string>
  </array>

  <key>WorkingDirectory</key>
  <string>$ROOT</string>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>

  <key>StandardOutPath</key>
  <string>$LOG</string>
  <key>StandardErrorPath</key>
  <string>$LOG</string>

  <key>EnvironmentVariables</key>
  <dict>
    <!-- launchd starts with a bare PATH; bd, tailscale and node may all be
         outside it. This covers Homebrew on both architectures plus the node
         found at install time. -->
    <key>PATH</key>
    <string>$(dirname "$NODE"):/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
</dict>
</plist>
PLIST_EOF

# --------------------------------------------------------------------- load it

say "loading the service"
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"
launchctl kickstart -k "gui/$(id -u)/$LABEL"

# Give it a moment to bind before we claim it works.
for _ in $(seq 1 20); do
  sleep 0.5
  if curl -fsS -m 2 http://127.0.0.1:4318/api/health >/dev/null 2>&1; then READY=1; break; fi
done

if [ "${READY:-}" != "1" ]; then
  die "the service did not come up. Check $LOG"
fi

WORKSPACES="$(curl -fsS -m 5 http://127.0.0.1:4318/api/health | sed 's/.*"workspaces":\[//;s/\].*//')"
say "running — workspaces: ${WORKSPACES:-none}"

echo
say "pair your phone (needs Tailscale on both devices):"
( cd "$ROOT" && node bin/beadcause.js --qr ) || true

cat <<NEXT

Useful from here:
  tail -f $LOG
  launchctl kickstart -k gui/$(id -u)/$LABEL     # restart after changing lib/ or bin/
  npm run uninstall-service                      # remove it again

Config (token, ntfy topic, workspaces) lives in ~/.config/beadcause/config.json.
NEXT
