#!/usr/bin/env bash
#
# Install beadcause as a login-time background service on macOS.
#
#   npm run install-service
#
# Everything machine-specific is discovered here rather than committed: the plist is
# generated with *this* user's home, node binary and checkout path. A checked-in
# plist cannot work on a second machine — node alone moves between
# /opt/homebrew/bin, /usr/local/bin and a dozen nvm paths.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LABEL="m4m.beadcause"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
# A second agent, opt-in, that opens the advocate console in a browser window at
# login. Separate from the daemon on purpose: the daemon must come up headless and
# stay up, whereas this fires once, opens a window and exits.
MONITOR_LABEL="$LABEL.monitor"
MONITOR_PLIST="$HOME/Library/LaunchAgents/$MONITOR_LABEL.plist"
LOG="$HOME/Library/Logs/beadcause.log"
LEGACY_LABELS=("com.neadamthal.beadcause" "com.beadcause" "n8l.beadcause")

say()  { printf '\033[1m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m warn\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31merror\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- prerequisites

[ "$(uname -s)" = "Darwin" ] || die "this installer is macOS-only (it uses launchd)."

NODE="$(command -v node || true)"
[ -n "$NODE" ] || die "node not found. Install Node 20+ (brew install node) and re-run."
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || die "node $NODE_MAJOR is too old; beadcause needs 20+."

# launchd starts with a bare PATH, so `bd` has to be found by absolute path or live
# somewhere the plist's PATH covers. Fail now rather than at the first poll.
BD="$(command -v bd || true)"
[ -n "$BD" ] || die "the beads CLI (bd) is not on your PATH. Install it first — beadcause is a front-end for it."

if [ ! -d "$HOME/beads" ]; then
  warn "no ~/beads directory: beadcause serves every ~/beads/*/.beads workspace and will find none."
fi

command -v tailscale >/dev/null 2>&1 || \
  warn "tailscale not found. beadcause binds to 127.0.0.1 and your Tailscale IP; without it, only this Mac can reach it."

# ------------------------------------------------------------------- dependencies

say "installing dependencies"
( cd "$ROOT" && npm install --silent )

# ------------------------------------------------------------------- configure

# Writes ~/.config/beadcause/config.json on first run, then asks the few things
# that cannot be guessed. Skips itself when there is no TTY.
( cd "$ROOT" && node scripts/configure.js < /dev/tty ) || \
  warn "configuration skipped — run 'npm run configure' later to set it up."

# ------------------------------------------------------------ migrate old install

# Labels this service has been known by. Leaving an old one loaded would leave two
# daemons fighting over port 4318 — the loser exits, but which one loses is a race.
for legacy in "${LEGACY_LABELS[@]}"; do
  legacy_plist="$HOME/Library/LaunchAgents/$legacy.plist"
  if launchctl list 2>/dev/null | grep -q "$legacy" || [ -f "$legacy_plist" ]; then
    say "removing the previous $legacy service (now $LABEL)"
    launchctl bootout "gui/$(id -u)/$legacy" 2>/dev/null || true
    rm -f "$legacy_plist"
  fi
done

# ------------------------------------------------------------------ monitor flag

# Asked by configure.js. Read after it runs so the answer takes effect immediately.
MONITOR_ENABLED="$(cd "$ROOT" && node -e '
  import("./lib/config.js")
    .then((m) => process.stdout.write(m.loadConfig().monitor?.enabled ? "1" : "0"))
    .catch(() => process.stdout.write("0"));
' 2>/dev/null || echo 0)"

# --------------------------------------------------------------------- the plist

say "writing $PLIST"
mkdir -p "$HOME/Library/LaunchAgents" "$(dirname "$LOG")"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/install.sh. Re-run it rather than editing by hand. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>

  <!-- The router, not the server. It owns the port and supervises a backend on an
       internal one, so an edit to lib/ is picked up by swapping the backend rather
       than by you remembering to restart. See bin/router.js. -->
  <key>ProgramArguments</key>
  <array>
    <string>$NODE</string>
    <string>$ROOT/bin/router.js</string>
  </array>

  <key>WorkingDirectory</key>
  <string>$ROOT</string>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>

  <key>StandardOutPath</key>
  <string>$LOG</string>
  <key>StandardErrorPath</key>
  <string>$LOG</string>

  <key>EnvironmentVariables</key>
  <dict>
    <!-- launchd starts with a bare PATH; bd, tailscale and node may all be
         outside it. This covers Homebrew on both architectures plus the node
         found at install time. -->
    <key>PATH</key>
    <string>$(dirname "$NODE"):/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
</dict>
</plist>
PLIST_EOF

# --------------------------------------------------------------------- load it

say "loading the service"
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"
launchctl kickstart -k "gui/$(id -u)/$LABEL"

# Give it a moment to bind before we claim it works.
for _ in $(seq 1 20); do
  sleep 0.5
  if curl -fsS -m 2 http://127.0.0.1:4318/api/health >/dev/null 2>&1; then READY=1; break; fi
done

if [ "${READY:-}" != "1" ]; then
  die "the service did not come up. Check $LOG"
fi

WORKSPACES="$(curl -fsS -m 5 http://127.0.0.1:4318/api/health | sed 's/.*"workspaces":\[//;s/\].*//')"
say "running — workspaces: ${WORKSPACES:-none}"

# ------------------------------------------------------------- the monitor agent

# Always tear the old one down first, so answering "no" in configure actually
# removes the window rather than leaving a stale agent loaded from last time.
launchctl bootout "gui/$(id -u)/$MONITOR_LABEL" 2>/dev/null || true
rm -f "$MONITOR_PLIST"

if [ "$MONITOR_ENABLED" = "1" ]; then
  say "writing $MONITOR_PLIST"
  cat > "$MONITOR_PLIST" <<MONITOR_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/install.sh. Re-run it rather than editing by hand. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$MONITOR_LABEL</string>

  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$ROOT/scripts/open-monitor.sh</string>
  </array>

  <key>WorkingDirectory</key>
  <string>$ROOT</string>

  <!-- Fires once at login, opens a window and exits. KeepAlive would relaunch it
       the moment it finished and open a new window every few seconds. -->
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <false/>

  <key>StandardOutPath</key>
  <string>$LOG</string>
  <key>StandardErrorPath</key>
  <string>$LOG</string>

  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>$(dirname "$NODE"):/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    <!-- open-monitor.sh reads the port and token out of config.json with node,
         and a login-time PATH may not have the one this was installed with. Pin it. -->
    <key>BEADCAUSE_NODE</key>
    <string>$NODE</string>
  </dict>
</dict>
</plist>
MONITOR_EOF

  # RunAtLoad means bootstrap opens the window straight away, which is also the
  # only honest way to prove the whole path works — daemon up, token readable,
  # browser willing.
  launchctl bootstrap "gui/$(id -u)" "$MONITOR_PLIST"
  say "the advocate console opens at login (and just opened) — http://127.0.0.1:4318/monitor"
else
  say "console not opened at login — visit /monitor when you want it"
fi

echo
say "pair your phone (needs Tailscale on both devices):"
( cd "$ROOT" && node bin/beadcause.js --qr ) || true

cat <<NEXT

Useful from here:
  tail -f $LOG
  open http://127.0.0.1:4318/monitor             # the advocate console
  npm run monitor                                # the same thing in a terminal, roughly
  npm run swap:status                            # which build is actually answering
  npm run swap                                   # swap now, without waiting
  launchctl kickstart -k gui/$(id -u)/$LABEL     # only needed for bin/router.js itself

Editing lib/ no longer needs a restart: the router notices within a few seconds and
swaps the backend under the port, draining the old one. The exception is
bin/router.js, which cannot replace itself — it says so in the log when it changes.

  npm run uninstall-service                      # remove it again

Config (token, ntfy topic, workspaces) lives in ~/.config/beadcause/config.json.
NEXT
