//
// A transparency log, built here, so the RFC 6962 checks run against real trees.
// `lib/translog.js`, `test/translog.mjs`, `test/anchor.mjs`.
//
// The proofs are generated by the *recursive* definitions in RFC 6962 §2.1 — the ones
// written for a reader rather than for a machine — while `lib/translog.js` verifies with
// the iterative decomposition every production log uses. That is the point of doing it
// twice: two implementations agreeing on thousands of index/size pairs is evidence the
// verifier is right, where a helper that mirrored the verifier's own arithmetic would
// agree with it about the bugs too.
//
import crypto from 'node:crypto';

import { leafHash, nodeHash } from '../../lib/translog.js';

/** The largest power of two strictly below n — where RFC 6962 splits a tree. */
const split = (n) => Math.max(1, 2 ** (Math.ceil(Math.log2(n)) - 1));

/** `MTH(D[n])`, by the recursive definition. */
export function root(leaves) {
  if (!leaves.length) return crypto.createHash('sha256').digest();
  if (leaves.length === 1) return leaves[0];
  const k = split(leaves.length);
  return nodeHash(root(leaves.slice(0, k)), root(leaves.slice(k)));
}

/** `PATH(m, D[n])` — the audit path for one leaf. */
export function inclusionProof(m, leaves) {
  if (leaves.length <= 1) return [];
  const k = split(leaves.length);
  return m < k
    ? [...inclusionProof(m, leaves.slice(0, k)), root(leaves.slice(k))]
    : [...inclusionProof(m - k, leaves.slice(k)), root(leaves.slice(0, k))];
}

/** `PROOF(m, D[n])` — that the tree of m entries is a prefix of the tree of n. */
export function consistencyProof(m, leaves) {
  const sub = (m2, list, b) => {
    if (m2 === list.length) return b ? [] : [root(list)];
    const k = split(list.length);
    return m2 <= k ? [...sub(m2, list.slice(0, k), b), root(list.slice(k))] : [...sub(m2 - k, list.slice(k), false), root(list.slice(0, k))];
  };
  return sub(m, leaves, true);
}

/** A log of `n` entries, with the leaf hashes and everything derived from them. */
export function log(entries) {
  const leaves = entries.map((e) => leafHash(e));
  return {
    entries,
    leaves,
    size: leaves.length,
    root: root(leaves),
    at: (n) => root(leaves.slice(0, n)),
    inclusion: (i, n = leaves.length) => inclusionProof(i, leaves.slice(0, n)).map((h) => h.toString('base64')),
    consistency: (m, n = leaves.length) => consistencyProof(m, leaves.slice(0, n)).map((h) => h.toString('base64')),
  };
}

/** An Ed25519 signer, which is what the `note` format most often carries. */
export const logKey = () => crypto.generateKeyPairSync('ed25519');

/**
 * A signed checkpoint in the `note` format — origin, size, root, blank line, signatures.
 *
 * The signature covers the body *including* its trailing blank line, verbatim. Signing a
 * reassembled body instead is the mistake this helper exists to not make on the verifier's
 * behalf: it would agree with a verifier that reassembled it the same way, and with
 * nothing else in the world.
 */
export function checkpoint({ origin = 'beadcause.test/log', size, root: rootHash, key, name = 'beadcause.test', extra = [] }) {
  const body = [origin, String(size), Buffer.from(rootHash).toString('base64'), ...extra].join('\n') + '\n\n';
  const hint = crypto.createHash('sha256').update(name).digest().subarray(0, 4);
  const signature = crypto.sign(null, Buffer.from(body, 'utf8'), key.privateKey);
  return `${body}— ${name} ${Buffer.concat([hint, signature]).toString('base64')}\n`;
}
